#개발용 DB profile
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P31C201?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S08P31C201
    password: 9qQEoOSm2E
  config:
    activate:
      on-profile: local

---

#운영 DB profile
spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  config:
    activate:
      on-profile: dev